controller_frequency: 5.0
#planner_patience: 5.0
#controller_patience: 15.0
recovery_behavior_enabled: false
clearing_rotation_allowed: false

TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.0
  max_vel_theta: 1.2
  min_vel_theta: 0.0
  min_in_place_vel_theta: 0.2
  escape_vel: -0.10
  acc_lim_x: 1.0
  acc_lim_y: 1.0
  acc_lim_th: 2.0

  holonomic_robot: false
  yaw_goal_tolerance: 0.2 # about 11 degrees
  xy_goal_tolerance: 0.05 # 5 cm
  goal_distance_bias: 0.2
  path_distance_bias: 1.5

  heading_lookahead: 0.3
  meter_scoring: false
  heading_scoring: false
  heading_scoring_timestep: 0.1
  oscillation_reset_dist: 0.05
  occdist_scale: 0.05
  publish_cost_grid_pc: false

  sim_time: 1.7
  sim_granularity: 0.025
  angular_sim_granularity: 0.025
  vx_samples: 8
  vtheta_samples: 20
  dwa: true
  simple_attractor: false
  
