controller_frequency: 5.0
#planner_patience: 5.0
#controller_patience: 5.0
recovery_behavior_enabled: false
clearing_rotation_allowed: false

TrajectoryPlannerROS:
  max_vel_x: 0.2
  min_vel_x: 0.1
  max_rotational_vel: 2.0
  min_rotational_vel: 1.0
  min_in_place_rotational_vel: 1.0
  escape_vel: -0.10
  acc_lim_x: 0.5
  acc_lim_y: 0.5
  acc_lim_th: 0.75

  holonomic_robot: false
  yaw_goal_tolerance: 0.2 # about 12 degrees
  xy_goal_tolerance: 0.10 # 20 cm
  goal_distance_bias: 0.6
  path_distance_bias: 0.8

  heading_lookahead: 0.325
  meter_scoring: false
  heading_scoring: false
  oscillation_reset_dist: 0.05
  occdist_scale: 0.05
  publish_cost_grid_pc: false

  sim_time: 2.5
  sim_granularity: 0.1
  angular_sim_granularity: 0.1
  vx_samples: 6
  vtheta_samples: 20
  dwa: false
  
  

